"""empty message

Revision ID: e23aba732da1
Revises: 
Create Date: 2016-12-05 21:39:44.692000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23aba732da1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('permission',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_name', sa.Unicode(length=255), nullable=True),
    sa.Column('permission_desc', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'role.role_id'], ),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('lastname', sa.String(length=50), server_default=u'', nullable=True),
    sa.Column('email', sa.Unicode(length=255), server_default=u'', nullable=False),
    sa.Column('username', sa.Unicode(length=255), server_default=u'', nullable=False),
    sa.Column('password', sa.Unicode(length=255), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['role_id'], [u'role.role_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('permission')
    op.drop_table('role')
    # ### end Alembic commands ###
